---
version: 0
OS: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: script/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server
      timeout: 300
      runas: root
