version: 0.0
OS: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
    
  ApplicationStop:
    - location: scripts/start.sh
      timeout: 300
      runas: root
